---
title: "tasks"
author: "ben@kenaiwatershed.org"
date: "12/29/2020"
output: html_document
---

- General: for each markdown document and script, move/copy script in to this repo along with source and output data.

scripts:

- /Users/bmeyer/Dropbox/Chena_Data_2020/UAF_Data/2020_Analysis_And_Results/Analysis Scripts/2019 Drift Energy Density Results.Rmd

- /Users/bmeyer/Dropbox/Chena_Data_2020/UAF_Data/2020_Analysis_And_Results/Analysis Scripts/Published Markdown Pages/Chena Drift Permit Reporting.Rmd

- /Users/bmeyer/Dropbox/Chena_Data_2020/UAF_Data/2020_Analysis_And_Results/Analysis Scripts/Published Markdown Pages/Chena Drift temperature.Rmd

- /Users/bmeyer/Dropbox/Chena_Data_2020/UAF_Data/2020_Analysis_And_Results/Analysis Scripts/Published Markdown Pages/Chena Fire And Drift Data Analysis 2020.Rmd

- /Users/bmeyer/Dropbox/Chena_Data_2020/UAF_Data/2020_Analysis_And_Results/Analysis Scripts/Published Markdown Pages/Chena_Hydrolabs_EDA.Rmd

- /Users/bmeyer/Dropbox/Chena_Data_2020/UAF_Data/2020_Analysis_And_Results/Analysis Scripts/Published Markdown Pages/Chena-Fire---Drift-Data-Analysis-2020.Rmd
